### PR TITLE
- Fixed compatibility with RN 0.29.

### PR DESCRIPTION
**Pull request by avishayil**

### CODE REVIEW

**Comment by FearMediocrity** [comment]
@avishayil Can you add an updated read me to your pull request? 

Or, if you let me know what to add to MainApplication instead of:

`new FabricPackage(this)`

Then I'd be happy to do it.

**Comment by avishayil** [comment]
Just new FabricPackage()
:>

Sorry for the non-complete PR :>


On July 4, 2016 at 4:42:01 PM, James Pearson (notifications@github.com)
wrote:

@avishayil <https://github.com/avishayil> Can you add an updated read me to
your pull request?

Or, if you let me know what to add to MainApplication instead of:

new FabricPackage(this)

Then I'd be happy to do it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/corymsmith/react-native-fabric/pull/50#issuecomment-230293533>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAyekHzMChPYxDkO9yrKKy5Z1cU5hVFTks5qSQ2ngaJpZM4JDt7T>
.

**Comment by FearMediocrity** [comment]
I've done some informal testing on RN23 and RN29 and seems to work perfectly. Thanks for that @avishayil , you saved my ass :)

**Comment by avishayil** [comment]
Glad I could help :>

**Comment by corymsmith** [comment]
Thanks for this! Will have a look this afternoon

**Comment by corymsmith** [comment]
I had to also update the rnpm section of the package.json to update the `packageInstance`.

**Comment by corymsmith** [comment]
Just published 0.3.0 to NPM that includes these and fixes #49

**Pull request merged**
