### PR TITLE
Update iOS RN header paths

### PR DESCRIPTION
**Pull request by janicduplessis**
https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d moves header imports to `<React/*>`. This updates header include path and all imports so build works against react master (soon to be version 0.40.0).

TODO: update examples when 0.40 is out.

### CODE REVIEW

**Comment by makenova** [comment]
@janicduplessis what version of react-native did you test this with?

**Comment by janicduplessis** [comment]
I tested this on master a week ago which is now 0.40.0-rc.0

However after discussing it more we might change this a bit so this change is not tequired anymore to avoid breaking all 3rd party libs. There were also issues with archiving that are yet to be resolved. Ill update this in a few days if changes are still needed. See discussion in https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d#commitcomment-20054846 for more details. Yea

**Comment by JakeRawr** [comment]
Let's merge this. As of today, RN 0.40 is out

**Comment by corymsmith** [comment]
Does this still work on older versions? I've been too busy to check this out unfortunately

**Comment by janicduplessis** [comment]
Cool, I'll just update the header search paths, we don't need that change anymore since they are now copied in a directory that is included by default.

**Comment by janicduplessis** [comment]
And not this won't work on older versions sadly.

**Comment by janicduplessis** [comment]
There has been quite a bit of discussion around this breaking change but seems like it will stay like it is as making it not breaking adds too much complexity for not much gained.

**Comment by makenova** [comment]
So this will only work for 0.40 and up?

**Comment by janicduplessis** [comment]
@makenova Yes

**Comment by makenova** [comment]
Sorry, I really meant to ask how versions of this library will be tied to compatible versions of RN.
Peer dependency?

**Comment by janicduplessis** [comment]
@makenova For older versions of RN you'll have to use an older version of this library. I think what most libs do is just put something in the readme that tells what version of the library is compatible with what version of RN.

**Comment by makenova** [comment]
@janicduplessis I see. Thanks for the answer!

I guess I was hoping that there was a way to take advantage of the tooling so it could handle that.

**Comment by janicduplessis** [comment]
I don't think there is a way at the moment, it is definitely a pain point maybe a tool like react-native link could support this eventually.

**Comment by corymsmith** [comment]
I just released 0.4.0 that includes this

**Pull request merged**
