### PR TITLE
Add the ability to handle non-fatal JS errors, migrate iOS code into an Xcode project

### PR DESCRIPTION
**Pull request by lrettig**
1. You can now trap non-fatal (handled) JS errors using Crashlytics. See https://github.com/corymsmith/react-native-fabric/issues/9 for discussion.

2. The iOS code has been migrated into an Xcode project, which makes it easier to include it in a top level project.

### CODE REVIEW

**Comment by corymsmith** [comment]
@lrettig This is great, I'll check this out :)

Have you tried to use `rnpm link` with this update? Thats something I'd like to get sorted, if not I can create a separate issue to track it.

**Comment by lrettig** [comment]
I haven't but I don't think you need to do anything special to get rnpm to
work. Give it a shot and let me know what happens.

**Comment by sbycrosz** [comment]
Hi there, 
Crashlytics works with `rnpm link` out of of the box :+1: 

Question though, in your app where do you use the `recordError` method?
Did you put it inside `ErrorUtils.globalHandler`?

```
    const defaultHandler = (ErrorUtils.getGlobalHandler && ErrorUtils.getGlobalHandler()) || ErrorUtils._globalHandler;
    ErrorUtils.setGlobalHandler((error, isFatal) => {
      if (!isFatal) {
        Crashlytics.recordError(error);
      }
      defaultHandler(error, isFatal);
    });
```

**Comment by lrettig** [comment]
Hi @sbycrosz, good question. I assume you're talking about [the method discussed in this thread](http://stackoverflow.com/questions/30918349/how-to-catch-uncaught-exception-globally-in-react-native)? (Also discussed here: https://github.com/facebook/react-native/issues/1194.)

Your suggested code looks reasonable to me. I'm not sure I completely understand your second comment. What do you mean by isFatal handler, or `throw new Error()`?

In my code, I don't do anything this fancy. Basically, all of my critical code lives inside promise chains. I wrote my own global error handler and end each of my promise chains with `.then(null, myErrorHandler)`. The error handler checks for some common, expected errors which don't need to be reported as crashes, then sends everything else to crashlytics using `Crashlytics.recordError`.

I don't make any claims to catch _all JS errors_ (which is what the threads above discuss), since I know that my critical code is isolated in these promise chains. Also, it's important to make sure that the promise implementation you're using is [A+ compliant](https://promisesaplus.com/) so that errors are caught and propagated through the promise chain.

**Comment by corymsmith** [comment]
I'll do an npm release later today / tomorrow

**Comment by corymsmith** [comment]
@lrettig Just published 0.1.0 to NPM

**Comment by akilabala** [comment]
I'm using Crashlytics.recordError(err) in my catch{} to record non-fatal JS errors. However, the errors don't show up on my Fabric dashboard. Could anybody point me to some examples?

**Comment by corymsmith** [comment]
@akilabala are you in dev mode? If you're debugging all errors are caught by RN and shown in the Red Box screen. In production mode they should be logged.

**Comment by akilabala** [comment]
@corymsmith Thanks for your response. I'm in PROD mode - installed the app on my device via TestFlight.

**Comment by akilabala** [comment]
@corymsmith I did a stupid mistake! It's working now. Thanks!

**Pull request merged**
