### PR TITLE
[Android] Update dependencies and build tools.

### PR DESCRIPTION
**Pull request by serj-lotutovici**
* Use latest android gradle plugin
* Compile against latest sdk
* Use android build tools 23.0.3
* Add gradle wrapper

### CODE REVIEW

**Comment by jeremistadler** [comment]
@corymsmith @lrettig Could you please merge this? 👍

**Comment by corymsmith** [comment]
@serj-lotutovici @jeremistadler The one reason why I hadn't updated the targetSdk version was that I thought it may conflict with peoples existing targetSdk in their project if it was lower then this one. It also forces people into the new permissions model: https://developer.android.com/training/permissions/requesting.html

So I wasn't sure of the implications yet. Any thoughts?

**Comment by serj-lotutovici** [comment]
@corymsmith to avoid this we just need to remove the `targetSdkVersion` from the config. Normally this will make the library unopinionated regarding the consumers target version. Will update the pr

**Comment by vongohren** [comment]
@corymsmith ?

**Comment by corymsmith** [comment]
Hey sorry everyone, I've been slammed with other projects and haven't been using this lib for any of them. If someone wants to be a collaborator on this project it would help get PR's like this out faster.

**Comment by vongohren** [comment]
I can consider it, cause im currently using it and also batteling it! Especially with this issue: https://github.com/corymsmith/react-native-fabric/issues/121

**Pull request merged**
