### PR TITLE
Merge Twitterkit branch into master

### PR DESCRIPTION
**Pull request by ramilushev**

### CODE REVIEW

**Comment by corymsmith** [comment]
The main reason I haven't merged this in is because it will force people not using Twitter to install the Twitter libs, not an ideal experience

**Comment by ramilushev** [comment]
Perhaps we can bring the branch up to date with master?

**Comment by tkporter** [comment]
I can do that-- I need to use TwitterKit for an existing application with react-native-fabric. I'll get everything up to date with Master, add composeTweet to iOS and get callbacks for composeTweet iOS and Android working (completed/canceled/error)

I should have it done some time this week

**Comment by corymsmith** [comment]
Going to close this as I'm not planning on merging this in at this point

**Pull request closed without merging**
