### PR TITLE
Updated gradle & android project to use variables from root project

### PR DESCRIPTION
**Pull request by XenorPLxx**
I've used changes made to https://github.com/luggit/react-native-config/compare/master...Aranda-Cyber-Solutions-LLC:master?diff=split&name=master as a reference and updated android project so it builds on the React Native 0.56 without problems and it also uses global project variables if those are present.

### CODE REVIEW

**Comment by sibelius** [comment]
can you follow react-native-camera pattern https://github.com/react-native-community/react-native-camera/blob/master/android/build.gradle?

**Comment by XenorPLxx** [comment]
Do you mean `safeExtGet`?

**Comment by sibelius** [comment]
yep, and maybe the same defaults

**Comment by XenorPLxx** [comment]
Okay, I've updated PR to follow that pattern and confirm everything builds just fine in my React Native 0.56 project that uses `react-native-fabric`.

**Comment by sibelius** [comment]
tks for the PR

**Pull request merged**
